[package]
name = "mssql_client"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
decimal = { git = "https://github.com/danylaporte/dec19x5.git", package = "dec19x5" }
failure = "0.1"
futures = "0.1"
futures-locks = "0.3"
futures-state-stream = "0.1"
humantime = "1.2"
lazy_static = "1.3"
log = "0.4"
regex = "1.1"
tiberius = { git = "https://github.com/steffengy/tiberius.git", rev="74f453bc8280888df9ec1693d004faf1c24fa343" }
uuid = { version = "0.7", features = [ "serde", "v4" ] }

[dev-dependencies]
tokio = "0.1"
